name: DiscordSRV-Ascension
main: com.discordsrv.bukkit.loader.DiscordSRVBukkitLoader
version: @VERSION@
description: ""
authors: [Scarsz, Vankka]
load: STARTUP

# Marks the plugin non-legacy in versions 1.13 and above
# This does not mean that the plugin only supports 1.13
api-version: 1.13

softdepend: [
  # Permission + group providers
  Vault, LuckPerms,
  # Chat
  Chatty, LunaChat, TownyChat, VentureChat,
  # Other integrations
  PlaceholderAPI, Essentials,
  # Adventure
  ViaVersion
]

commands:
  discordsrv:
    description: "DiscordSRV's primary command"
