name: DiscordSRV
main: com.discordsrv.bukkit.loader.DiscordSRVBukkitLoader
version: @VERSION@
description: ""
authors: [Scarsz, Vankka]
load: STARTUP
api-version: 1.13

softdepend: [
  # Permission + group providers
  Vault, LuckPerms,
  # Chat
  Chatty, LunaChat, TownyChat, VentureChat,
  # Other integrations
  PlaceholderAPI,
  # Adventure
  ViaVersion
]

commands:
  discordsrv:
    description: "DiscordSRV's primary command"
