name: Crowdin translation download

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download translations from Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: false
          download_sources: false
          download_translations: true
          download_translations_args: "--verbose"

          localization_branch_name: i18n
          create_pull_request: true
          commit_message: "New Crowdin translations"
          pull_request_title: "New Crowdin translations"
          pull_request_base_branch_name: "main"

          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          source: "i18n/build/source.yaml"
          translation: "/i18n/build/%three_letters_code%.%file_extension%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
