name: Crowdin translation download

on:
  push:
    branches: [dev]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download translations from Crowdin
        uses: crowdin/github-action@1.4.8
        with:
          upload_translations: false
          download_translations: true
          localization_branch_name: i18n
          create_pull_request: true
          pull_request_title: "New Crowdin translations"
          pull_request_body: ""
          source: "source.yaml"
          translation: "/%original_path%/src/main/resources/translations/%two_letters_code%.yaml"
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
